title: "GetGo Fonts for FontLab"
logo: https://res.cloudinary.com/fontlab/image/fetch/f_auto,w_48,c_scale/https://www.fontlab.com/img/icon-fontlab-7.png
#theme: "just-the-docs"
#baseurl: /
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: false
kramdown:
  parse_block_html: true
heading_anchors: true
collections:
  pages:
    output: true
    permalink: /:path/

permalink: pretty

footer_content: "Site copyright &copy; 2021 Fontlab Ltd. Fonts are copyright of their respective rights owners. See license details for each font."
