title: GetGo Fonts for FontLab
description: The GetGo Fonts for FontLab is a collection of font files, which are suitable for starting your own font project in FontLab. The fonts are licensed under CC-0 (public domain), Apache or OFL, and are available for download in the FontLab VFJ format. They support a variety of writing systems and design styles, and the collection is growing!
baseurl: "/getgo-fonts"
url: "https://fontlabcom.github.io"
logo: https://res.cloudinary.com/fontlab/image/fetch/f_auto,w_48,c_scale/https://www.fontlab.com/img/icon-fontlab-7.png
#theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
kramdown:
  parse_block_html: true
heading_anchors: true
collections:
  pages:
    output: true
    permalink: /:path/
permalink: pretty

search_enabled: true

search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

footer_content: "Site copyright &copy; 2021 <a target='_blank' href='https://www.fontlab.com/'>Fontlab Ltd</a>. Fonts are copyright of their respective rights owners. See license details for each font. "
